---
- name: create bashrc.d
  file: path={{ ansible_env.HOME}}/bashrc.d/
        force=yes
        state=directory
- name: master config .bashrc
  template:
   src=bashrc.j2
   dest=~/.bashrc
- name: rest of the configs
  template:
    src={{ item }}.j2
    dest=~/bashrc.d/{{ item }}
  with_items:
    - prompt.bash
