---
- name: create bashrc.d
  file: path={{ ansible_env.HOME}}/bashrc.d/
        force=yes
        state=directory
- name: master config .bashrc
  template:
   src=bashrc.j2
   dest=~/.bashrc
- name: rest of the configs
  template:
    src={{ item }}.j2
    dest=~/bashrc.d/{{ item }}
  with_items:
    - prompt.bash
    - default.bash
- name: clone z
  git: repo=https://github.com/rupa/z.git
       dest={{ ansible_env.HOME}}/z
- name: install z
  file:
    src: '{{ ansible_env.HOME}}/z/z.sh'
    dest: '{{ ansible_env.HOME}}/bashrc.d/z.bash'
    state: link
