---
- hosts: all
  pre_tasks:
  - group_by: key=os_{{ ansible_distribution }}
  - name: install
    package: name={{item}} state=latest
    become: true
    with_items:
    - "{{ sudo }}"
    - "{{ tree }}"
    - "{{ ag }}"
    - "{{ mc }}"
    - "{{ links }}"
    - "{{ jq }}"
    - "{{ asciinema }}"
    - "{{ bind_utils }}"
    - "{{ aspell }}"
    - "{{ aspell_en }}"
    - "{{ iptraf_ng }}"

  roles:
  - tmux
  - vim
  - git
  - bash
  - fish
  - cpp
  - debug
  - ansible

