#!/bin/bash
base_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function get_sudo()
{
   local sudo=
   if [[ $(/usr/bin/id -u) -ne 0 ]]; then
       sudo=sudo
       timeout 2 sudo -n id || sudo=gksudo

       $sudo -H --preserve-env bash $0 "$@"
       exit $?
   fi
}

function install()
{
   local pkg_mgr='echo Install before running: '
   get_sudo

   type yum 2> /dev/null > /dev/null && {
      pkg_mgr="yum install -y "
   }

   type apt 2> /dev/null > /dev/null && {
      pkg_mgr="apt install -y "
   }

   type pacman 2> /dev/null > /dev/null && {
      pkg_mgr="pacman -Sy --noconfirm "
   }

   $pkg_mgr "$@"
}

type ansible-playbook 2> /dev/null > /dev/null || {
  type yum 2> /dev/null > /dev/null && install "epel-release"

  install "python"
  install "ansible"
}

type git 2> /dev/null > /dev/null || {
  install "git"
}

cd $base_dir

current_home=`cd;pwd`
current_user=`whoami`

ansible-playbook -v -i hosts -become-method=sudo --ask-become-pass -e current_user=${current_user} -e current_home=${current_home} -e level='basic' local.yml

