#!/bin/bash
base_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

type ansible-playbook > /dev/null || {
  sudo yum install -y ansible
  sudo pacman -Sy --noconfirm  ansible
}

cd $base_dir
git submodule update --init --recursive
ansible-playbook -v -i hosts -e level='basic' thenv.yml


