---
#- name: install cppman
#  command: python {{ ansible_env.PWD }}/roles/cpp/template/cppman/setup.py install
- name: install
  package: name={{item}} state=latest
  become: true
  with_items:
  - libstdc++-docs
  - gcc
  - clang
