---
- name: install
  package: name={{item}} state=latest
  become: true
  with_items:
  - gcc
  - clang
  - python-pip
  - ccache
- name: pip install cppman
  pip:
    name: "{{item}}"
  become: true
  with_items:
  - bs4
  - html5lib
  - cppman

