---
- name: install
  package: name=git state=latest
  become: true
- template:
   src: gitconfig.j2
   dest: ~/.gitconfig
- name: clone source
  git: repo=https://github.com/git/git.git
       dest={{ ansible_env.HOME}}/git
  when: level == 'full'
- name: dependencies for build
  package: name={{item}} state=latest
  become: true
  with_items:
    - openssl-devel
    - libcurl-devel
    - expat-devel
    - perl-devel
  when: level == 'full'
- name: build
  make: chdir={{ ansible_env.HOME}}/git/
        target=all
  when: level == 'full'

