---
- name: install
  package: name=vim state=latest
  become: true
- template:
    src: vimrc.j2
    dest: ~/.vimrc
- name: create .vim directory
  file: dest=~/.vim/{{ item }}
        state=directory
  with_items:
  - doc
  - plugin
- name: git clone
  git:
    repo: https://github.com/tpope/vim-fugitive.git
    dest: ~/.vim/vim-fugitive
- name: link vim-fugitive
  file: src={{ ansible_env.HOME }}/.vim/vim-fugitive/{{ item }}
        dest={{ ansible_env.HOME}}/.vim/{{ item }}
        state=link
  with_items:
  - plugin/fugitive.vim
  - doc/fugitive.txt
