---
- name: install
  package: name=vim state=latest
  become: true
- template:
    src: vimrc.j2
    dest: "{{ current_home }}/.vimrc"
- name: create .vim directory
  file: dest={{ current_home }}/.vim/{{ item }}
        state=directory
  with_items:
  - doc
  - plugin
- name: git clone
  git:
    repo: https://github.com/tpope/vim-fugitive.git
    dest: "{{ current_home }}/.vim/vim-fugitive"
