
name: CI

on: [pull_request, push]

jobs:
  archlinux:
    runs-on: ubuntu-latest
    container: dock0/arch
    steps:
    - uses: actions/checkout@v1
    - name: execute once
      run: ./thenv
    - name: execute twice
      run: ./thenv
  ubuntu-latest:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
    - name: apt update
      run: apt update
    - uses: actions/checkout@v1
    - name: execute once
      run: ./thenv
    - name: execute twice
      run: ./thenv
  debian-latest:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
    - name: apt update
      run: apt update
    - uses: actions/checkout@v1
    - name: execute once
      run: ./thenv
    - name: execute twice
      run: ./thenv
  centos-7:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: install epel-release
      run: yum install -y epel-release
    - uses: actions/checkout@v1
    - name: execute once
      run: ./thenv
    - name: execute twice
      run: ./thenv


